name: Deploy

on: workflow_dispatch

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  deploy-on-runner:
    runs-on: self-hosted
    steps:
      - name: Delete old ajor-xui-exporter container
        run: docker rm -f ajor-xui-exporter
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run and pull new image
        run: |
          docker run -d --name ajor-xui-exporter \
          --restart always \
          --network host \
          -e XPANEL_URL=${{ secrets.XPANEL_URL }} \
          -e XPANEL_USERNAME=${{ secrets.XPANEL_USERNAME }} \
          -e XPANEL_PASSWORD=${{ secrets.XPANEL_PASSWORD }} \
          -e APP_LOG_MODE=${{ vars.APP_LOG_MODE }} \
          -e APP_SCRAPE_TIME=${{ vars.APP_SCRAPE_TIME }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ vars.APP_VERSION }}
